// Joke API URL
const JOKE_API_URL = 'https://v2.jokeapi.dev/joke/Any';

// DOM Elements
const jokeText = document.getElementById('jokeText');
const generateBtn = document.getElementById('generateBtn');
const shareBtn = document.getElementById('shareBtn');
const loading = document.getElementById('loading');

// Event listeners
generateBtn.addEventListener('click', fetchJoke);
shareBtn.addEventListener('click', shareJoke);

/**
 * Fetch a random joke from the API
 */
async function fetchJoke() {
    try {
        // Show loading state
        showLoading(true);
        generateBtn.disabled = true;
        shareBtn.style.display = 'none';

        // Fetch joke from API
        const response = await fetch(JOKE_API_URL);
        
        if (!response.ok) {
            throw new Error(`API Error: ${response.status}`);
        }

        const data = await response.json();

        // Display the joke
        displayJoke(data);
        
        // Show share button
        shareBtn.style.display = 'block';

    } catch (error) {
        console.error('Error fetching joke:', error);
        jokeText.textContent = '❌ Oops! Failed to load a joke. Please try again.';
        jokeText.style.color = '#e74c3c';
    } finally {
        // Hide loading state
        showLoading(false);
        generateBtn.disabled = false;
    }
}

/**
 * Display the joke based on type (single or two-part)
 */
function displayJoke(jokeData) {
    let jokeContent = '';
    
    if (jokeData.type === 'single') {
        // Single-part joke
        jokeContent = jokeData.joke;
    } else if (jokeData.type === 'twopart') {
        // Two-part joke (setup and delivery)
        jokeContent = `${jokeData.setup}\n\n${jokeData.delivery}`;
    }

    // Store current joke for sharing
    window.currentJoke = jokeContent;

    // Display the joke with animation
    jokeText.style.color = '#333';
    jokeText.textContent = jokeContent;
    
    // Add fade-in animation
    jokeText.style.animation = 'none';
    setTimeout(() => {
        jokeText.style.animation = 'fadeIn 0.5s ease-in';
    }, 10);
}

/**
 * Show/hide loading spinner
 */
function showLoading(isLoading) {
    if (isLoading) {
        loading.style.display = 'block';
        jokeText.style.display = 'none';
    } else {
        loading.style.display = 'none';
        jokeText.style.display = 'block';
    }
}

/**
 * Share the current joke
 */
function shareJoke() {
    if (!window.currentJoke) return;

    const jokeTweet = `Check out this joke: "${window.currentJoke}" 😂\n\nGenerated by Joke Generator!`;
    
    // Try to use native Web Share API if available
    if (navigator.share) {
        navigator.share({
            title: 'Check out this joke!',
            text: window.currentJoke,
        }).catch(err => console.log('Share cancelled:', err));
    } else {
        // Fallback: Copy to clipboard
        navigator.clipboard.writeText(window.currentJoke).then(() => {
            showNotification('Joke copied to clipboard!');
        }).catch(() => {
            showNotification('Failed to copy joke');
        });
    }
}

/**
 * Show temporary notification
 */
function showNotification(message) {
    const originalText = shareBtn.textContent;
    shareBtn.textContent = message;
    
    setTimeout(() => {
        shareBtn.textContent = originalText;
    }, 2000);
}

// Add fade-in animation CSS
const style = document.createElement('style');
style.textContent = `
    @keyframes fadeIn {
        from {
            opacity: 0;
        }
        to {
            opacity: 1;
        }
    }
`;
document.head.appendChild(style);

// Load a joke when page loads
window.addEventListener('load', () => {
    // Optional: fetch a joke automatically on load
    // fetchJoke();
});
